# A method and a list are passed to Python's map() function.
#
# The function is executed for all of the elements within the list, and a new list is produced with elements generated by the given function for every item.

# square of all elements

list1=[2,4,6,8]
myList=list(map(lambda item:item**2,list1))
print(myList)